# Generated by Django 5.1.4 on 2025-02-04 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modular', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgenteWazuh',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('ip', models.CharField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('passed_policies', models.IntegerField()),
                ('failed_policies', models.IntegerField()),
                ('na_policies', models.IntegerField()),
                ('last_scan', models.DateTimeField(blank=True, null=True)),
                ('policy_name', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
