# Generated by Django 4.2.20 on 2025-04-28 01:24

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('modular', '0003_agentetest_delete_agente_delete_agentewazuh'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyChecksTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_id_in_policy', models.PositiveIntegerField(help_text='ID numérico del check dentro de la política de prueba')),
                ('policy_id_test', models.CharField(db_index=True, help_text='ID de la política de prueba (e.g., laboratorio_computo_windows)', max_length=255)),
                ('result', models.CharField(help_text='Resultado del check (passed, failed, etc.)', max_length=50)),
                ('remediation', models.TextField(blank=True, help_text='Remediación sugerida')),
                ('command', models.TextField(blank=True, help_text='Comando ejecutado')),
                ('description', models.TextField(blank=True, help_text='Descripción del check')),
                ('title', models.CharField(help_text='Título del check', max_length=255)),
                ('condition', models.CharField(blank=True, help_text='Condición de evaluación (all, any, none)', max_length=50)),
                ('rationale', models.TextField(blank=True, help_text='Justificación del check', null=True)),
                ('compliance_json', models.JSONField(default=list, help_text='Mapeo de cumplimiento (formato JSON)')),
                ('rules_json', models.JSONField(default=list, help_text='Reglas del check (formato JSON)')),
                ('date_recorded', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent_test', models.ForeignKey(help_text='Agente de prueba al que pertenece este check', on_delete=django.db.models.deletion.CASCADE, related_name='policy_checks_test', to='modular.agentetest')),
            ],
            options={
                'verbose_name': 'Policy Check (Test Data)',
                'verbose_name_plural': 'Policy Checks (Test Data)',
                'ordering': ['agent_test', 'policy_id_test', 'check_id_in_policy'],
            },
        ),
    ]
