# Generated by Django 4.2.20 on 2025-04-28 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modular', '0004_policycheckstest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cve',
            fields=[
                ('id', models.CharField(help_text='Identificador único del CVE (e.g., CVE-2017-0144)', max_length=50, primary_key=True, serialize=False)),
                ('risk_percentage', models.PositiveIntegerField(blank=True, help_text='Riesgo calculado como porcentaje entero (0-100)', null=True)),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='Última vez que se actualizó el riesgo')),
            ],
            options={
                'verbose_name': 'CVE',
                'verbose_name_plural': 'CVEs',
                'ordering': ['-risk_percentage', 'id'],
            },
        ),
    ]
