# Generated by Django 4.2.20 on 2025-05-02 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modular', '0005_cve'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentFailedCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(db_index=True, help_text='ID del agente Wazuh o AgenteTest', max_length=255)),
                ('check_id', models.PositiveIntegerField(help_text='ID del check de política (ej: 1, 2, 3...)')),
                ('policy_id', models.CharField(db_index=True, help_text="ID de la política (ej: 'laboratorio_computo_windows', 'cis_win11')", max_length=255)),
                ('last_seen', models.DateTimeField(auto_now=True, help_text='Timestamp de cuándo se confirmó por última vez que este check estaba fallido')),
            ],
            options={
                'verbose_name': 'Check Fallido Actual',
                'verbose_name_plural': 'Checks Fallidos Actuales',
                'ordering': ['agent_id', 'policy_id', 'check_id'],
                'unique_together': {('agent_id', 'check_id', 'policy_id')},
            },
        ),
    ]
