# Generated by Django 4.2.20 on 2025-07-21 04:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('modular', '0006_currentfailedcheck'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentFailedChecksSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failed_checks_count', models.PositiveIntegerField(help_text='Cantidad de checks fallidos registrados en este momento.')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se registró este resumen.')),
                ('agent', models.ForeignKey(help_text='Agente al que pertenece este resumen de checks fallidos.', on_delete=django.db.models.deletion.CASCADE, related_name='failed_checks_summaries', to='modular.agentetest')),
            ],
            options={
                'verbose_name': 'Resumen de Checks Fallidos del Agente',
                'verbose_name_plural': 'Resúmenes de Checks Fallidos del Agente',
                'ordering': ['-timestamp'],
            },
        ),
    ]
