# Generated by Django 4.2.20 on 2025-07-21 05:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('modular', '0007_agentfailedcheckssummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalFailedChecksHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_failed_count', models.PositiveIntegerField(help_text='Cantidad total de checks fallidos en el sistema en este momento.')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se registró este total global.')),
            ],
            options={
                'verbose_name': 'Historial Global de Checks Fallidos',
                'verbose_name_plural': 'Historiales Globales de Checks Fallidos',
                'ordering': ['-timestamp'],
            },
        ),
    ]
