# Generated by Django 4.2.20 on 2025-09-09 22:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modular', '0008_globalfailedcheckshistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agentetest',
            old_name='policy_name',
            new_name='policy_id',
        ),
    ]
