# Generated by Django 4.2.20 on 2025-09-09 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modular', '0009_rename_policy_name_agentetest_policy_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentetest',
            name='policy_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
