# Generated by Django 4.2.20 on 2025-09-11 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modular', '0010_agentetest_policy_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policycheckstest',
            name='agent_test',
        ),
        migrations.RemoveField(
            model_name='agentfailedcheckssummary',
            name='agent',
        ),
        migrations.AddField(
            model_name='agentfailedcheckssummary',
            name='agent_id',
            field=models.CharField(db_index=True, default=1, help_text='ID del agente Wazuh o AgenteTest', max_length=255),
        ),
        migrations.DeleteModel(
            name='AgenteTest',
        ),
        migrations.DeleteModel(
            name='PolicyChecksTest',
        ),
    ]
