# Generated by Django 4.2.20 on 2025-09-11 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modular', '0011_remove_policycheckstest_agent_test_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentfailedcheckssummary',
            name='agent_id',
            field=models.CharField(blank=True, default=1, help_text='ID del agente Wazuh o AgenteTest', max_length=255, null=True),
        ),
    ]
